version: 0.1
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=javaplayground1234 -Dsonar.organization=java-reachable-goof -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=e8addc749a4b1d4658c84d21a224ed2fe711d7b4
