version: 0.1
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=java -Dsonar.organization=gratt410 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=5b6ab94d66cd9e8898f03a6824becfaed31d1ead
